---
- name: clone rfcat repository
  git: 
    repo: https://github.com/atlas0fd00m/rfcat.git
    dest: /opt/rfcat
    version: master

- name: install dependencies
  shell: |
    pip install -r /opt/rfcat/requirements.txt
    pip install "jedi<0.18.0"
    ln -s /opt/rfcat/rfcat /usr/local/bin/rfcat
  
- name: download sdcc 3.5.0
  get_url:
    url: https://netactuate.dl.sourceforge.net/project/sdcc/sdcc-linux-x86/3.5.0/sdcc-3.5.0-i386-unknown-linux2.5.tar.bz2
    dest: /opt/sdcc-3.5.0.tar.bz2
    mode: 0755

- name: extract sdcc
  unarchive:
    src: /opt/sdcc-3.5.0.tar.bz2
    dest: /opt

- name: symbolically link sdcc
  shell: | 
    ln -s /opt/sdcc-3.5.0/bin/* /usr/local/bin
    ln -s /opt/sdcc-3.5.0/share/* /usr/local/share

- name: enable usb access without elevated privileges
  lineinfile:
    create: yes
    group: root
    line: 'SUBSYSTEM=="usb",MODE="0666"'
    mode: '0644'
    owner: root
    path: /etc/udev/rules.d/usb.rules
    regexp: 'SUBSYSTEM=="usb",MODE="0666"'
...
