---
- name: create nrf sniffer directory
  file:
    path: /opt/nrf
    state: directory
    mode: '0655'
    owner: root
    group: root

- name: create nrf sniffer installer directory
  file:
    path: /opt/nrf-deb
    state: directory
    mode: '0655'
    owner: root
    group: root

- name: Extract nrf.zip into /opt/nrf
  unarchive:
    src: https://www.nordicsemi.com/-/media/Software-and-other-downloads/Desktop-software/nRF-Sniffer/sw/nrfsnifferforbluetoothle3107cc811f.zip
    dest: /opt/nrf
    remote_src: yes

- name: Extract nrf.zip into /opt/nrf-deb
  unarchive:
    src: https://www.nordicsemi.com/-/media/Software-and-other-downloads/Desktop-software/nRF-command-line-tools/sw/Versions-10-x-x/10-12-1/nRFCommandLineTools10121Linuxamd64tar.gz
    dest: /opt/nrf-deb
    remote_src: yes

- name: Install nrf-command-line-tools
  apt: deb="/opt/nrf-deb/nRF-Command-Line-Tools_10_12_1_Linux-amd64.deb"

- name: Install JLink
  apt: deb="/opt/nrf-deb/JLink_Linux_V688a_x86_64.deb"

- name: copy wireshark configuration files
  shell: |
    if [ ! -d /usr/lib/x86_64-linux-gnu/wireshark/extcap/SnifferAPI ]; then
      cp -r /opt/nrf/extcap/*  /usr/lib/x86_64-linux-gnu/wireshark/extcap
    fi
    if [ ! -d  /usr/share/wireshark/profiles/Profile_nRF_Sniffer_Bluetooth_LE ]; then
      cp -r /opt/nrf/Profile_nRF_Sniffer_Bluetooth_LE  /usr/share/wireshark/profiles
    fi

- name: enable tty access without elevated privileges
  lineinfile:
    create: yes
    group: root
    line: 'SUBSYSTEM=="tty",MODE="0666"'
    mode: '0644'
    owner: root
    path: /etc/udev/rules.d/usb.rules
    regexp: 'SUBSYSTEM=="tty",MODE="0666"'
...



